[project]
name = "mlqtl"
version = "0.1.0"
description = "A Python package for QTL detection based on machine learning"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.2.3",
    "scikit-learn>=1.6.1",
]
